# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
      autowire: true
      autoconfigure: true
      public: false

    Psr\Log\LoggerInterface: '@logger'

    custom_doctrine_orm_naming_strategy_underscore:
      class: Doctrine\ORM\Mapping\UnderscoreNamingStrategy
      arguments:
        - 0
        - true

    AppBundle\:
      resource: '../../src/AppBundle/*'
      exclude: '../../src/AppBundle/{Entity,Repository}'